I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label d2_t0 is defined twice, at File "game/story/hallowed winds/hw_day_1.rpy", line 409:
label d2_t0:
and File "game/story/hallowed winds/hw_day_2.rpy", line 528:
label d2_t0:


Ren'Py Version: Ren'Py 8.1.3.23091805
Tue Mar 12 14:45:22 2024
