I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/introduction/hw_day_1.rpy", line 253, in script
    python:
  File "game/story/introduction/hw_day_1.rpy", line 254, in <module>
    forum.load_full_thread(forum.story_thread)
  File "game/persistant code/managers.rpy", line 271, in load_full_thread
    if self.has_battery_interaction(thread_info):
  File "game/persistant code/managers.rpy", line 255, in has_battery_interaction
    social_cost = thread_info.social_cost
AttributeError: 'int' object has no attribute 'social_cost'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/introduction/hw_day_1.rpy", line 253, in script
    python:
  File "C:\Users\carol\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\carol\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/story/introduction/hw_day_1.rpy", line 254, in <module>
    forum.load_full_thread(forum.story_thread)
  File "game/persistant code/managers.rpy", line 271, in load_full_thread
    if self.has_battery_interaction(thread_info):
  File "game/persistant code/managers.rpy", line 255, in has_battery_interaction
    social_cost = thread_info.social_cost
AttributeError: 'int' object has no attribute 'social_cost'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Production 1.0
Sat Mar  9 20:07:34 2024
